(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBylineInfoAssets@core","DetailPageBylineInfo"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(p){var d=window.AmazonUIPageJS||window.P,v=d._namespace||d.attributeErrors,n=v?v("SocialShareWidgetAUI","AmazonUI"):d;n.guardFatal?n.guardFatal(p)(n,window):n.execute(function(){p(n,window)})})(function(p,d,v){var n="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(d){return typeof d}:function(d){return d&&"function"===typeof Symbol&&d.constructor===Symbol&&d!==Symbol.prototype?"symbol":typeof d};p.register("SocialShareWidget",function(){return function(d){function a(c){if(e[c])return e[c].exports;
var b=e[c]={i:c,l:!1,exports:{}};return d[c].call(b.exports,b,b.exports,a),b.l=!0,b.exports}var e={};return a.m=d,a.c=e,a.d=function(c,b,f){a.o(c,b)||Object.defineProperty(c,b,{enumerable:!0,get:f})},a.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},a.t=function(c,b){if((1&b&&(c=a(c)),8&b)||4&b&&"object"==("undefined"===typeof c?"undefined":n(c))&&c&&c.__esModule)return c;var f=
Object.create(null);if(a.r(f),Object.defineProperty(f,"default",{enumerable:!0,value:c}),2&b&&"string"!=typeof c)for(var l in c)a.d(f,l,function(a){return c[a]}.bind(null,l));return f},a.n=function(c){var b=c&&c.__esModule?function(){return c.default}:function(){return c};return a.d(b,"a",b),b},a.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},a.p="",a(a.s=6)}([function(k,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.isCSALoaded=a.isNativeAppShareAvailable=a.isNativeWebShareAvailable=
a.isMobileWeb=a.isMobileApp=a.isDesktop=a.isIOS=a.isAndroid=a.isIE=a.isAUILoaded=a.isUeAvailable=a.isTwisterAsin=a.context=a.Device=void 0;var c,b=e(4);!function(a){a.Android="apan";a.IOS="apin";a.MWeb="mwn";a.Other="ud"}(c=a.Device||(a.Device={}));a.context=function(){var b=c.Other;return(0,a.isMobileApp)()&&(0,a.isAndroid)()?b=c.Android:(0,a.isMobileApp)()&&(0,a.isIOS)()?b=c.IOS:(0,a.isMobileWeb)()&&(b=c.MWeb),{device:b,page:(0,a.isUeAvailable)()?d.ue_pty:"unknown",subPage:(0,a.isUeAvailable)()?
d.ue_spty||d.ue_pti:"unknown"}};a.isTwisterAsin=function(){return!!d.isTwisterPage||!!d.twisterController||f};a.isUeAvailable=function(){return!!d.ue};a.isAUILoaded=function(){var a;return(0,b.isString)(null===(a=null===d||void 0===d?void 0:d.P)||void 0===a?void 0:a.AUI_BUILD_DATE)};a.isIE=function(){return(0,b.testUserAgent)(/MSIE|Trident/i)};a.isAndroid=function(){return(0,b.testUserAgent)(/android.([1-9]|[L-Z])/i)&&!(0,b.testUserAgent)(/trident|Edge/i)};a.isIOS=function(){return(0,b.testUserAgent)(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&
!(0,b.testUserAgent)(/trident|Edge/i)};a.isDesktop=function(){return!((0,a.isAndroid)()||(0,a.isIOS)()||(0,a.isMobileApp)()||(0,a.isMobileWeb)())};a.isMobileApp=function(){return/(Windowshop|Amazon|Amazon\.com)\//.test((0,b.getCookie)("amzn-app-id"))};a.isMobileWeb=function(){return 450>=d.screen.availWidth&&((0,b.testUserAgent)(/mobile|mini/i)||(0,a.isAndroid)()||(0,a.isIOS)())};a.isNativeWebShareAvailable=function(){return d.navigator&&(0,b.isFunction)(d.navigator.share)};a.isNativeAppShareAvailable=
function(a){return a&&(0,b.isFunction)(a.share)};a.isCSALoaded=function(){return(0,b.isFunction)(d.csa)};var f=!1;(0,a.isAUILoaded)()&&d.P.when("mobile-inline-twister-critical").execute(function(){f=!0});a.default={context:a.context,isTwisterAsin:a.isTwisterAsin,isUeAvailable:a.isUeAvailable,isAUILoaded:a.isAUILoaded,isIE:a.isIE,isAndroid:a.isAndroid,isDesktop:a.isDesktop,isIOS:a.isIOS,isMobileApp:a.isMobileApp,isMobileWeb:a.isMobileWeb,isNativeWebShareAvailable:a.isNativeWebShareAvailable,isNativeAppShareAvailable:a.isNativeAppShareAvailable,
isCSALoaded:a.isCSALoaded}},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.CHANNEL_TO_REF_MAP=a.defaultShareDataAttributes=a.SHARE_TYPE_TO_CHANNEL=a.EMPTY_STRING=a.DEFAULT_CSA_REF_ID=a.CSA_DEFAULT_VALUE=a.CSA_HIT_TYPE=void 0;(function(a){a.CLICK_SUCCESS="click_success";a.CLICK_ERROR="click_error";a.CLICK_CANCEL="click_cancel";a.SHARE="share"})(a.CSA_HIT_TYPE||(a.CSA_HIT_TYPE={}));a.CSA_DEFAULT_VALUE={string:"unknown",number:0,boolean:2};a.DEFAULT_CSA_REF_ID="u_";a.EMPTY_STRING=
"";a.SHARE_TYPE_TO_CHANNEL={"com.google.android.gm.ComposeActivityGmail":"Email","com.android.email.activity.MessageCompose":"Email","com.google.android.gm.ComposeActivityGmailExternal":"Email","com.twitter.android.composer.TextFirstComposerActivity":"Twitter","com.twitter.android.composer.ComposerActivity":"Twitter","com.twitter.app.dm.DMActivity":"Twitter","com.android.mms.ui.ConversationComposer":"SMS","com.android.mms.ui.ComposeMessageActivity":"SMS","com.whatsapp.contact.picker.ContactPicker":"WhatsApp",
"com.weico.international.activity.compose.SeaComposeActivity":"Weibo","com.google.android.apps.messaging.ui.conversationlist.ShareIntentActivity":"SMS","com.facebook.composer.shareintent.ImplicitShareIntentHandlerDefaultAlias":"Facebook","com.facebook.composer.shareintent.ImplicitShareIntentHandler":"Facebook","com.facebook.messenger.activity.ShareLauncherActivity":"FacebookMessenger","com.whatsapp.ContactPicker":"WhatsApp","com.sina.weibo.EditActivity":"Weibo","com.sina.weibo.composerinde.ComposerDispatchActivity":"Weibo",
"com.pinterest.activity.create.PinItActivity":"Pinterest","jp.naver.line.android.activity.selectchat.SelectChatActivity":"Line","com.linecorp.line.share.common.view.FullPickerLaunchActivity":"Line","com.google.android.apps.docs.drive.clipboard.SendTextToClipboardActivity":"Copy","com.instagram.direct.share.handler.DirectShareHandlerActivity":"Instagram","com.snap.mushroom.MainActivity":"Snapchat"};a.defaultShareDataAttributes={isInternal:a.CSA_DEFAULT_VALUE.boolean,isRobot:a.CSA_DEFAULT_VALUE.boolean,
userAgent:a.CSA_DEFAULT_VALUE.number,platform:a.CSA_DEFAULT_VALUE.string,ingress:a.CSA_DEFAULT_VALUE.string,asin:a.CSA_DEFAULT_VALUE.string,requestId:a.CSA_DEFAULT_VALUE.string,customerId:a.CSA_DEFAULT_VALUE.string,marketplaceId:a.CSA_DEFAULT_VALUE.string};(function(a){a.Weibo="si";a.Twitter="tw";a.SMS="sm";a.Email="em";a.Facebook="fb";a.Copy="cp";a.TencentWeibo="tc";a.AirDrop="ar";a.WhatsApp="wa";a.Line="li";a.Pinterest="pi";a.FacebookMessenger="fm";a.Gmail="em";a.WeChat="we";a.WeChatMoment="wm"})(a.CHANNEL_TO_REF_MAP||
(a.CHANNEL_TO_REF_MAP={}))},function(k,a,e){Object.defineProperty(a,"__esModule",{value:!0});var c=e(3);k=function(){function a(f,b){this.REF_PARAM_NAME="ref_";a.isValid(f)||(f=a.getDefault());this.url=new URL(f);this._refMarker=new c.default(b)}return a.prototype.getUpdatedUrl=function(a){var c=new URL(this.raw);return c.searchParams.set(this.REF_PARAM_NAME,a),c.toString()},Object.defineProperty(a.prototype,"raw",{get:function(){return this.url.toString()},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,
"refMarker",{get:function(){return this._refMarker},enumerable:!1,configurable:!0}),a.isValid=function(a){try{new URL(a)}catch(l){return!1}return!0},a.getDefault=function(){var a,c,b=null===(a=null===d||void 0===d?void 0:d.location)||void 0===a?void 0:a.href;return b?(a=new URL(b),a.search="",a.href):d.ue_pti&&b?d.location.origin+"/dp/"+d.ue_pti:(null===(c=null===d||void 0===d?void 0:d.ue)||void 0===c?0:c.sn)?"https://"+d.ue.sn:"https://amazon.com"},a.prototype.getReturnForChannel=function(a){a=this._refMarker.getReturnForChannel(a);
return this.getUpdatedUrl(a)},a.prototype.getClickForChannel=function(a){a=this._refMarker.getClickForChannel(a);return this.getUpdatedUrl(a)},Object.defineProperty(a.prototype,"return",{get:function(){return this.getUpdatedUrl(this._refMarker.return)},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"click",{get:function(){return this.getUpdatedUrl(this._refMarker.click)},enumerable:!1,configurable:!0}),a}();a.default=k},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});
var c,b=e(0);!function(a){a.RETURN="r";a.CLICK="cl"}(c||(c={}));d=function(){function a(a){if(void 0===a&&(a="ur"),this.PREFIX="cm_sw",this.id="",this.refId="",this.cxt={device:b.Device.Other,page:"",subPage:""},2>a.length)throw new TypeError("refId must be 2 or more characters long");this.refId=a;this.cxt=(0,b.context)();this.generateUniqueId()}return Object.defineProperty(a.prototype,"return",{get:function(){return this.get(c.RETURN)},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,
"click",{get:function(){return this.get(c.CLICK)},enumerable:!1,configurable:!0}),a.prototype.getReturnForChannel=function(a){return this.PREFIX+"_"+c.RETURN+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a.prototype.getClickForChannel=function(a){return this.PREFIX+"_"+c.CLICK+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a.prototype.generateUniqueId=function(){for(var a="",c=0;13>c;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));
return this.id=a},a.prototype.get=function(a){return this.PREFIX+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a}();a.default=d},function(k,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.getDPXObject=a.getCookie=a.testUserAgent=a.truncate=a.isString=a.isEmpty=a.isNumber=a.isFunction=void 0;a.isFunction=function(a){return"function"==typeof a};a.isNumber=function(a){return!isNaN(a)&&"number"==typeof a};a.isEmpty=function(a){return!a||!a.length};a.isString=function(a){return"string"==
typeof a};a.truncate=function(a,b){void 0===a&&(a="");var c=Array(3).fill(".");return a.length>b?a.substring(0,b-3)+c.join(""):a};a.testUserAgent=function(a){if(!d&&!d.navigator)return!1;try{return a.test(d.navigator.userAgent)}catch(b){return!1}};a.getCookie=function(a){var b;if(d.ue)return null===(b=d.ue.cookie)||void 0===b?void 0:b.get(a);a+="\x3d";b=document.cookie.split(";");for(var c=0;c<b.length;c++){for(var l=b[c];" "==l.charAt(0);)l=l.substring(1);if(0==l.indexOf(a))return l.substring(a.length,
l.length)}return""};a.getDPXObject=function(){var a,b;return null===(b=null===(a=d.DetailPage)||void 0===a?void 0:a.StateController)||void 0===b?void 0:b.state};a.default={isFunction:a.isFunction,isNumber:a.isNumber,isEmpty:a.isEmpty,isString:a.isString,truncate:a.truncate,testUserAgent:a.testUserAgent,getCookie:a.getCookie,getDPXObject:a.getDPXObject}},function(k,a,e){Object.defineProperty(a,"__esModule",{value:!0});var c=e(0),b=e(9);k=function(){function a(){}return a.logCounter=function(a){(0,
c.isUeAvailable)()&&(a=this.BASE_METRIC_NAME+"."+a,d.ue.count(a,(d.ue.count(a)||0)+1))},a.logFatal=function(a){(0,c.isAUILoaded)()&&d.P.log(a,"FATAL",this.BASE_METRIC_NAME)},a.logRefMarker=function(a){this.logFatal(a)},a.logCSAEvent=function(a,d){(0,c.isCSALoaded)()&&(new b.default).withCSAClickEventData(d).withShareHitType(a).logEvent()},a.startTimer=function(){d.uet&&(0,c.isUeAvailable)()&&d.uet("bb",this.BASE_METRIC_NAME,{wb:1})},a.stopTimer=function(){d.uet&&(0,c.isUeAvailable)()&&d.uet("be",
this.BASE_METRIC_NAME,{wb:1});d.uex&&(0,c.isUeAvailable)()&&d.uex("ld",this.BASE_METRIC_NAME,{wb:1})},a.BASE_METRIC_NAME="SocialShareFramework",a}();a.default=k},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.SocialShareCore=void 0;d=e(7);var c=e(2),b=e(8),f=e(5),l=e(10),w=e(3),h=e(0);e=e(1);a.SocialShareCore={Channels:d.default,Url:c.default,Translations:b.default,Metrics:f.default,ShareSheet:l.default,RefMarker:w.default,Detection:h.default,Constants:e};a.default=a.SocialShareCore},
function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.default=function(a,b){var c={email:{label:"Email",name:"email",ref:"em",shareBaseUrl:"mailto:",image:"https://m.media-amazon.com/images/G/01/share-icons/email-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/email-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){var b="?subject\x3d"+encodeURIComponent(a.title),c="\x26body\x3d"+encodeURIComponent(a.text)+" "+encodeURIComponent(a.url.getReturnForChannel(this.ref));
return""+this.shareBaseUrl+b+c}},pi:{label:"Pinterest",name:"pinterest",ref:"pi",shareBaseUrl:"https://www.pinterest.com/pin/create/button",image:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-squared.svg",canOpenInPopup:!0,getSharingUrl:function(){var b="?url\x3d"+encodeURIComponent(a.url.getReturnForChannel(this.ref)),c="\x26description\x3d"+encodeURIComponent(a.text),d="\x26media\x3d"+encodeURIComponent(a.image);
return""+this.shareBaseUrl+b+c+d}},li:{label:"Line",name:"line",ref:"li",shareBaseUrl:"https://social-plugins.line.me/lineit/share",image:"https://m.media-amazon.com/images/G/01/share-icons/line-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/line-squared.svg",canOpenInPopup:!0,getSharingUrl:function(){return encodeURIComponent(a.title)+" "+encodeURIComponent(a.text)+" "+(""+encodeURIComponent(a.url.getReturnForChannel(this.ref)))}},fb:{label:"Facebook",name:"facebook",
ref:"fb",shareBaseUrl:"https://www.facebook.com/dialog/share",image:"https://m.media-amazon.com/images/G/01/share-icons/facebook-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/facebook-squared.svg",canOpenInPopup:!0,getSharingUrl:function(){var b=encodeURIComponent(a.url.getReturnForChannel(this.ref));b=["?_encoding\x3dUTF8\x26app_id\x3d465632727431967\x26display\x3dpopup","href\x3d"+b,"redirect_uri\x3d"+b,"hashtag\x3d"+encodeURIComponent("#"+(a.hashtags[0]||"Amazon"))].join("\x26");
return""+this.shareBaseUrl+b}},tw:{label:"Twitter",name:"twitter",ref:"tw",shareBaseUrl:"https://twitter.com/intent/tweet",image:"https://m.media-amazon.com/images/G/01/share-icons/twitter-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/twitter-squared.svg",canOpenInPopup:!0,getSharingUrl:function(){var b="?text\x3d"+encodeURIComponent(a.url.getReturnForChannel(this.ref)),c="\x26hashtags\x3d"+a.hashtags.join(","),d="\x26via\x3d"+encodeURIComponent("Amazon");return""+
this.shareBaseUrl+b+c+d}},wa:{label:"WhatsApp",name:"whatsapp",ref:"wa",shareBaseUrl:"https://api.whatsapp.com/send?text\x3d",image:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-squared.svg",canOpenInPopup:!0,getSharingUrl:function(){var b="\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(a.text)+"\n              "+encodeURIComponent(a.url.getReturnForChannel(this.ref));
return""+this.shareBaseUrl+b}},sms:{label:"SMS",name:"sms",ref:"sms",shareBaseUrl:"sms:",image:"https://m.media-amazon.com/images/G/01/share-icons/sms-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/sms-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){var b="\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(a.url.getReturnForChannel(this.ref));return""+this.shareBaseUrl+b}},copy:{label:"Copy",name:"copy",ref:"cp",shareBaseUrl:"",
image:"https://m.media-amazon.com/images/G/01/share-icons/link-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/link-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){return""}}};if(null==b?0:b.length){var d={};return b.forEach(function(a){c[a]&&(d[a]=c[a])}),d}return c}},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.default={}},function(k,a,e){Object.defineProperty(a,"__esModule",{value:!0});var c=e(0),b=e(1);k=function(){function a(){var c=
this;this.generateTimestampCollection=function(){var a=(new Date).getTimezoneOffset();a=c.getDateTimeByOffset(a);var b=c.getDateTimeByOffset(0);return{hitDay:a.split("T")[0],hitDatetime:a,hitDatetimeUtc:b}};this.getMarketplaceId=function(a){return"string"==typeof a?a:d.ue&&d.ue.mid?d.ue.mid:b.CSA_DEFAULT_VALUE.string};var e=this.generateTimestampCollection();this.csaMetricsData={schemaId:a.CSA_SCHEMA_ID,userAgentId:b.CSA_DEFAULT_VALUE.number,hitDay:e.hitDay,hitDatetime:e.hitDatetime,hitDatetimeUtc:e.hitDatetimeUtc,
pageType:d.ue_pty?d.ue_pty:b.CSA_DEFAULT_VALUE.string,subPageType:d.ue_spty?d.ue_spty:b.CSA_DEFAULT_VALUE.string,sessionId:d.ue&&d.ue.sid?d.ue.sid:b.CSA_DEFAULT_VALUE.string}}return a.prototype.withCSAClickEventData=function(a){var c=a.shareDataAttributes;return this.csaMetricsData.customerId=c.customerId?c.customerId:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.httpRequestId=c.requestId?c.requestId:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.asin=c.asin?c.asin:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.ingress=
c.ingress?c.ingress:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.platform=c.platform?c.platform:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.isInternal=c.isInternal?c.isInternal:b.CSA_DEFAULT_VALUE.boolean,this.csaMetricsData.isRobot=c.isRobot?c.isRobot:b.CSA_DEFAULT_VALUE.boolean,this.csaMetricsData.channel=a.channel?a.channel:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.refMarker=a.refMarker?a.refMarker:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.referrerUrl=a.refererURL?a.refererURL:b.CSA_DEFAULT_VALUE.string,
this.csaMetricsData.marketplaceId=this.getMarketplaceId(c.marketplaceId),this},a.prototype.withShareHitType=function(a){return this.csaMetricsData.shareHitType=a||b.CSA_DEFAULT_VALUE.string,this},a.prototype.getDateTimeByOffset=function(b){var c=new Date;0!==b&&(b*=a.MINUTES_TO_MILISECONDS,c=c.getTime()-b,c=new Date(c));return c.toISOString().split("Z")[0].split(".")[0]},a.prototype.logEvent=function(){(0,c.isCSALoaded)()&&d.csa(a.CSAPluginId,{producerId:a.CSA_PRODUCER_ID})(a.CSA_LOG_EVENT,this.csaMetricsData)},
a.MINUTES_TO_MILISECONDS=6E4,a.CSAPluginId="Events",a.CSA_PRODUCER_ID="social-share",a.CSA_LOG_EVENT="log",a.CSA_SCHEMA_ID="SocialShareCSACustomEvent.CSAShareMetrics.5",a}();a.default=k},function(k,a,e){var c=this&&this.__assign||function(){return(c=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++)for(var e in b=arguments[c])Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e]);return a}).apply(this,arguments)};Object.defineProperty(a,"__esModule",{value:!0});var b=e(5),f=e(0),
l=e(2),w=e(4),h=e(1);k=function(){function a(a){var b=this;this.sheetOptions={title:h.EMPTY_STRING,text:h.EMPTY_STRING,shareUrl:new l.default("http://amazon.com/","ur"),lang:"en",shareDataAttributes:h.defaultShareDataAttributes,refererURL:""};(0,f.isAUILoaded)()&&d.P.when("mash").execute(function(a){return b.mash=a});this.sheetOptions=c(c({},this.sheetOptions),a);this.shareUrl=a.shareUrl}return a.prototype.launchNativeWeb=function(){var a,c={channel:h.EMPTY_STRING,refMarker:this.shareUrl.refMarker.click,
refererURL:this.sheetOptions.refererURL,shareDataAttributes:this.sheetOptions.shareDataAttributes};try{null===(a=null===d||void 0===d?void 0:d.navigator)||void 0===a||a.share({url:this.shareUrl.return,title:this.sheetOptions.title,text:this.sheetOptions.text}).then(function(){b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_SUCCESS,c);b.default.logCSAEvent(h.CSA_HIT_TYPE.SHARE,c)}).catch(function(){b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_SUCCESS,c);b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_CANCEL,c)})}catch(m){b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_ERROR,
c)}},a.prototype.launchNativeApp=function(){var a,d=this,e={channel:h.EMPTY_STRING,refMarker:this.shareUrl.refMarker.click,refererURL:this.sheetOptions.refererURL,shareDataAttributes:this.sheetOptions.shareDataAttributes},f={messagePlain:this.getShareMessage,messagePlain160:this.getShare160Message,messagePlain140:this.getShare140Message,messageHTML:this.getShareMessage,url:this.shareUrl.return,subject:this.sheetOptions.text};null===(a=this.mash)||void 0===a||a.share(c(c({},f),{successCallback:function(){b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_SUCCESS,
e)},failCallback:function(){b.default.logCSAEvent(h.CSA_HIT_TYPE.CLICK_ERROR,e)},shareServiceSelectedCallback:function(a){if(a){a=d.getChannelForSharingType(a);var c=d.getRefIdForChannel(a);c=d.shareUrl.refMarker.getClickForChannel(c);e.refMarker=c;e.channel=a;b.default.logCSAEvent(h.CSA_HIT_TYPE.SHARE,e)}else b.default.logCSAEvent(a?h.CSA_HIT_TYPE.SHARE:h.CSA_HIT_TYPE.CLICK_CANCEL,e)}}))},a.prototype.launch=function(a){(0,f.isNativeAppShareAvailable)(this.mash)?this.launchNativeApp():(0,f.isNativeWebShareAvailable)()?
this.launchNativeWeb():(0,w.isFunction)(a)?a():b.default.logCounter("Log something that says sharing isn't available")},Object.defineProperty(a.prototype,"getShare160Message",{get:function(){var a=this.shareUrl.return,b=a.length+2;return(0,w.truncate)(this.sheetOptions.title,160-b)+"\n    "+a},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"getShare140Message",{get:function(){var a=this.shareUrl.return,b=a.length+2;return(0,w.truncate)(this.sheetOptions.title,140-b)+"\n    "+a},
enumerable:!1,configurable:!0}),a.prototype.getChannelForSharingType=function(a){var b=a;return(0,f.isAndroid)()&&(b=h.SHARE_TYPE_TO_CHANNEL[a]?h.SHARE_TYPE_TO_CHANNEL[a]:h.CSA_DEFAULT_VALUE.string),b},a.prototype.getRefIdForChannel=function(a){return h.CHANNEL_TO_REF_MAP[a]?h.CHANNEL_TO_REF_MAP[a]:h.DEFAULT_CSA_REF_ID},Object.defineProperty(a.prototype,"getShareMessage",{get:function(){return this.shareUrl.return+"\n    "+this.sheetOptions.title},enumerable:!1,configurable:!0}),a}();a.default=k}])});
"use strict";p.register("SocialShareWidgetConfig",function(){return{excludedChannels:["sms","wa"],defaultShareData:{url:"",title:"Amazon.com",text:"Check this out!",image:"",hashtags:["Amazon"],type:"popover",lang:"en",refId:"ts",channels:[],refererURL:"",t:{}},defaultWidgetData:{icon:"ios",background:!1,viewTreatment:"BADGE",width:25,shareDataAttributes:{isInternal:2,isRobot:2,userAgent:"",platform:"",ingress:"",asin:"",requestId:"",customerId:"",marketplaceId:""}},iconMap:{ios:"https://m.media-amazon.com/images/G/01/share-icons/share-ios.svg",
android:"https://m.media-amazon.com/images/G/01/share-icons/share-android.svg"}}});"use strict";p.when("A","SocialShareWidget","SocialShareWidgetTemplating","SocialShareWidgetConfig").register("SocialShareWidgetAUI",function(k,a,e,c){var b=a.SocialShareCore,f=b.Metrics;f.startTimer();f.logCounter("DPX.Desktop.ImageBlockRender");try{(function(){var a=k.$,w=b.Detection,h=b.Translations,v=b.Channels,n=b.Url,A=b.Constants,m=c.defaultShareData,q=a(".ssf-share-trigger");q.each(function(b,c){a(c).addClass("ssf-multi-"+
Math.random().toString(36).slice(2))});var x=q.data("share")||{},D=x=k.extend({},c.defaultWidgetData,x),t=D.shareDataAttributes,B=D.refererURL,C=function(a){return isNaN(Number(a))?2:Number(a)},r=void 0,g=void 0,u=void 0,y=void 0,z=void 0;p.when("a-sheet").execute(function(a){return r=a});p.when("a-popover").execute(function(a){return g=a});p.when("a-modal").execute(function(a){return u=a});var H=function(a){var b=a.shareData,c="popover"===b.type&&g,d="modal"===b.type&&u;a=e.build({channels:a.channels,
shareData:b,t:a.t});r?(c=a.getBottom(),q.hasClass("a-declarative")||(y=r.create({name:"ssf-share-bottom-sheet",inlineContent:c,height:400,closeType:"icon"})),r.showSheet(y)):c?(c=a.getPopover(),q.hasClass("a-declarative")||(z=g.create(q,{name:"ssf-share-popover",position:"triggerBottom",inlineContent:c,activate:"onclick",closeButton:!1,popoverArrow:!1,width:160,padding:"none",popoverLabel:"Share Popup",closeButtonLabel:"Close Share Popup"}).show())):d&&(c=a.getModal(),q.hasClass("a-declarative")||
u.create(q,{inlineContent:c}).show())},F=function(){z&&g.get(q).hide();y&&r.hideSheet(y)};a(document).delegate(".ssf-channel:not(.copy)","click",function(b){b.preventDefault();b.stopPropagation();f.logCounter("DPX.Desktop.ChannelClick");var c=a(this),e=c.data("ref");b=c.attr("href");c=c.data("name");var g="cm_sw_cl_"+e.replace("fb","fa")+"_dp_T2_"+m.shareDataAttributes.requestId;f.logCSAEvent(A.CSA_HIT_TYPE.SHARE,{channel:c,refMarker:g,refererURL:B,shareDataAttributes:t});if("em"===e)d.open(b,"_self");
else if(w.isDesktop()){e=screen.width;c=screen.height;g=Math.min(600,.7*e);var h=Math.min(600,.7*c);d.open(b,"_blank","toolbar\x3d0,status\x3d0,width\x3d"+g+",height\x3d"+h+",top\x3d"+(c/2-h/2)+",left\x3d"+(e/2-g/2))}else d.open(b,"_blank");F()});k.declarative("ssf-share-icon","click",function(b){f.logCounter("DPX.Desktop.SheetClick");f.logCounter("DPX.Desktop.T2Click");m=k.extend(m,b.data);m.shareDataAttributes&&(t=m.shareDataAttributes,t.isRobot=C(t.isRobot),t.isInternal=C(t.isInternal));q=a(b.$currentTarget).find("[class*\x3d'ssf-multi-']");
b=m.url||n.getDefault();m.url=m.url instanceof n?m.url:new n(b,m.refId+"_T2");f.logCSAEvent(A.CSA_HIT_TYPE.CLICK_SUCCESS,{channel:A.EMPTY_STRING,refMarker:m.url.refMarker.click,refererURL:B,shareDataAttributes:t});b=k.extend(h[m.lang],m.t);var c=v(m,m.channels);f.logCounter("DPX.Desktop.SheetOpen");H({shareData:m,t:b,channels:c});w.isDesktop()||(q.addClass("ssf-noclick"),k.delay(function(){q.removeClass("ssf-noclick")},1E3))});a(document).delegate(".ssf-copy,.ssf-channel.copy","click",function(b){f.logCounter("DPX.Desktop.ChannelClick");
var c="cm_sw_cl_cp_ud_dp_T2_"+m.shareDataAttributes.requestId,e=d.location.origin+"/dp/"+m.shareDataAttributes.asin+"?ref_\x3d"+("cm_sw_r_cp_ud_dp_"+m.shareDataAttributes.requestId);b.preventDefault();var g={channel:"copy",refMarker:c,shareDataAttributes:t};navigator.clipboard.writeText(e).then(function(){a(".ssf-feedback").show();f.logCSAEvent(A.CSA_HIT_TYPE.SHARE,g);f.logCounter("DPX.Desktop.CopySuccess");F()},function(){f.logCSAEvent(A.CSA_HIT_TYPE.CLICK_ERROR,g);f.logCounter("DPX.Desktop.CopyFailure")})});
x=x.width;D=a('[data-action\x3d"ssf-share-icon"]');var G=a("[id$\x3d'mageBlock_feature_div']"),I=a("#ppd #leftCol"),E=1.5*x;E=a('\x3cdiv class\x3d"ssf-background"\x3e\x3c/div\x3e').css({width:E,height:E});a(".ssf-background").length||q.wrap(E);"sticky"!==I.css("position")&&G.css("position","relative");G.prepend(D);q.css({height:x,width:x,display:"inline-block"});w.isIE()&&a(".ssf-share-trigger,.ssf-background").remove();k.on("a:popover:afterUpdatePosition:ssf-share-popover",function(a){a=a.popover.$popover;
var b=a.position().left-60;a.css({left:b})})})()}catch(l){f.logCounter("DPX.Desktop.Error"),f.logFatal("Error loading Share Framework AUI: "+l.toString())}finally{f.logCounter("DPX.Desktop.Render"),f.stopTimer()}});"use strict";var z=function(){return function(d,a){if(Array.isArray(d))return d;if(Symbol.iterator in Object(d)){var e=[],c=!0,b=!1,f=v;try{for(var l=d[Symbol.iterator](),k;!(c=(k=l.next()).done)&&(e.push(k.value),!a||e.length!==a);c=!0);}catch(h){b=!0,f=h}finally{try{if(!c&&l["return"])l["return"]()}finally{if(b)throw f;
}}return e}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();p.when("A","SocialShareWidgetConfig").register("SocialShareWidgetTemplating",function(d,a){var e=d.$,c=!!navigator.clipboard&&"function"===typeof navigator.clipboard.writeText,b=a.excludedChannels;c||b.push("copy");return{build:function(a){var d=a.channels,f=a.shareData,h=a.t;f.socialLinks.email=f.mailToUri;var k='\x3cspan class\x3d"a-button ssf-copy"\x3e\n      \x3cspan class\x3d"a-button-inner"\x3e\n        \x3cinput class\x3d"a-button-input" type\x3d"submit"\x3e\n        \x3cspan class\x3d"a-button-text" aria-hidden\x3d"true"\x3e\n          \x3cdiv\x3e'+
h.taf_copy_tooltip+"\x3c/div\x3e\n        \x3c/span\x3e\n      \x3c/span\x3e\n    \x3c/span\x3e";c&&1>e(".ssf-feedback").length&&e(document.body).append('\x3cdiv class\x3d"a-changeover ssf-feedback"\x3e\n          \x3cdiv class\x3d"a-changeover-inner"\x3e\n            \x3ci class\x3d"a-icon a-icon-checkmark-inverse"\x3e\x3c/i\x3e\n            \x3cstrong class\x3d"a-size-medium"\x3e'+h.taf_copy_url_changeover+"\x3c/strong\x3e\n          \x3c/div\x3e\n        \x3c/div\x3e");var n=f.url,p=f.socialLinks;
return{getModal:function(){var a="",e=!0,f=!1,l=v;try{for(var t=Object.entries(d)[Symbol.iterator](),B;!(e=(B=t.next()).done);e=!0){var C=z(B.value,2),r=C[0],g=C[1];b.includes(r)||"copy"===r||(g.titleString=h["taf_"+g.name+"_tooltip"],g.dpxLink=p[g.name]||g.getSharingUrl(),a+='\x3cdiv class\x3d"ssf-channel-h"\x3e\n            \x3ca class\x3d"ssf-channel a-color-base" href\x3d"'+g.dpxLink+'" title\x3d"'+g.titleString+'" data-name\x3d"'+g.name+'" data-ref\x3d"'+g.ref+'"\x3e\n              \x3ci role\x3d"img" aria-label\x3d"'+
g.label+'" style\x3d"background-image: url('+g.image+')"\x3e\x3c/i\x3e\n            \x3c/a\x3e\n            \x3cspan\x3e'+g.label+"\x3c/span\x3e\n          \x3c/div\x3e")}}catch(u){f=!0,l=u}finally{try{!e&&t.return&&t.return()}finally{if(f)throw l;}}return'\x3ch3 class\x3d"a-spacing-large"\x3e'+h.taf_share_bottom_sheet_title+"\x3c/h3\x3e"+('\x3cdiv class\x3d"ssf-h-icons"\x3e'+a+"\x3c/div\x3e")+(c?'\x3cdiv class\x3d"ssf-copy-section a-box a-padding-base a-spacing-top-large"\x3e\n              \x3cdiv class\x3d"link-section"\x3e'+
n.return+'\x3c/div\x3e\n              \x3cdiv class\x3d"copy-button"\x3e'+k+"\x3c/div\x3e\n          \x3c/div\x3e":"")},getPopover:function(){var a="",c=!0,e=!1,f=v;try{for(var k=Object.entries(d)[Symbol.iterator](),l;!(c=(l=k.next()).done);c=!0){var n=z(l.value,2),r=n[0],g=n[1];if(!(b.includes(r)||p.line&&"pi"===r||p.pinterest&&"li"===r)){var u="taf_"+g.name+"_name";g.titleString=h["taf_"+g.name+"_tooltip"];g.dpxLink=p[g.name]||g.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-v"\x3e\n              \x3ca class\x3d"ssf-channel '+
r+' a-color-base" href\x3d"'+g.dpxLink+'" title\x3d"'+g.titleString+'" data-name\x3d"'+g.name+'" data-ref\x3d"'+g.ref+'"\x3e\n                \x3ci role\x3d"img" aria-label\x3d"'+(h[u]||g.label)+'" style\x3d"background-image: url('+g.image+')"\x3e\x3c/i\x3e\n                \x3cspan\x3e'+(h[u]||g.label)+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}}catch(y){e=!0,f=y}finally{try{!c&&k.return&&k.return()}finally{if(e)throw f;}}return""+a},getBottom:function(){var a="",b=!0,e=
!1,f=v;try{for(var h=Object.entries(d)[Symbol.iterator](),k;!(b=(k=h.next()).done);b=!0){var l=z(k.value,2),n=l[0],g=l[1];if("copy"!==n||c)a+='\x3cdiv class\x3d"ssf-channel-b a-padding-base"\x3e\n              \x3ca class\x3d"ssf-channel '+n+' a-color-base" href\x3d"'+g.getSharingUrl()+'" data-name\x3d"'+g.name+'" href\x3d"'+g.getSharingUrl()+'" data-ref\x3d"'+g.ref+'"\x3e\n                \x3ci role\x3d"img" aria-label\x3d"'+g.label+'" style\x3d"background-image: url('+g.image+')"\x3e\x3c/i\x3e\n                \x3cspan class\x3d"a-size-base-plus"\x3e'+
g.label+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}catch(u){e=!0,f=u}finally{try{!b&&h.return&&h.return()}finally{if(e)throw f;}}return""+a}}}}})});
/* ******** */
