export const events = Object.freeze({
  LINK_CLICKED: 'link_clicked',
  BUTTON_CLICKED: 'button_clicked',
  EMAIL_DETAILS_EXPANDED: 'email_details_expanded',
  EMAIL_DETAILS_COLLAPSED: 'email_details_collapsed',
  MARKED_SCAM: 'marked_scam',
  MARKED_REAL: 'marked_real',
  FORM_SUBMITTED: 'form_submitted',
  EMAIL_REPLY: 'email_reply',
  EMAIL_REPLY_ALL: 'email_reply_all',
  EMAIL_FORWARD: 'email_forward',
  EMAIL_DOT_MENU: 'email_dot_menu',
  EMAIL_DELETE: 'email_delete',
  EMAIL_REPORT_SPAM: 'email_report_spam',
  EMAIL_ARCHIVE: 'email_archive',
  EMAIL_BACK: 'email_back',
  EMAIL_INBOX: 'email_inbox',
  EMAIL_FAVORITES: 'email_favorites',
  EMAIL_DRAFTS: 'email_drafts',
  EMAIL_SPAM: 'email_spam',
  BROWSER_BACK_CLICKED: 'browser_back_clicked',
  BROWSER_NEXT_CLICKED: 'browser_next_clicked',
  BROWSER_REFRESH_CLICKED: 'browser_refresh_clicked',
  BROWSER_HOME_CLICKED: 'browser_home_clicked',
  BROWSER_MARK_FAVORITE_CLICKED: 'browser_mark_favorite_clicked',
  BROWSER_DOTS_CLICKED: 'browser_dots_clicked',
  BROWSER_NEW_TAB_CLICKED: 'browser_new_tab_clicked',
  BROWSER_CLOSE_TAB_CLICKED: 'browser_close_tab_clicked',
});

export default events;
